### ISSUE TITLE
need upgrade to support python 3.10

### ISSUE THREAD

**Issue by zffocussss** [nameko/nameko#745]
**Please use the [Discourse forum](https://discourse.nameko.io/) for support requests and questions.**

**Describe the bug**

  File "/usr/local/lib/python3.10/site-packages/dns/namedict.py", line 35, in <module>
    class NameDict(collections.MutableMapping):
AttributeError: module 'collections' has no attribute 'MutableMapping'

**To Reproduce**
Steps to reproduce the behaviour, ideally a code sample.
when upgrading python from 3.9 to 3.10

**Expected behavior**

**Environment (please complete the following information):**
 - Nameko version: 2.14.0
 - Python version: python 3.10
 - OS: debian 10

**Additional context**
[dnspython](https://github.com/rthalley/dnspython) need to upgrade from 1.16.0 to 2.14.0

**Comment by PabloEmidio** [comment]
@zffocussss this issue should've been closed by now.
